### ISSUE TITLE
ALEX-2CDE and Export histogram and fit into CSV

### ISSUE THREAD

**Issue by mcraj31** [OpenSMFS/FRETBursts#22]
Hi,

Thanks for the great coding. I am new to coding I would appreciate your help.
1.  like stoichometry selection/filter, I wish to include Alex-2CDE filter in the final FRET histogram 
2. Fit works very well, how do I export the histogram and final model fit (entire iterations) so that I could use other program just to re-plot for publication quality figures. 

Thank you
Raj

**Comment by tritemio** [comment]
Hi @mcraj31,

1. you need to create your own selection function to select according to ALEX-2CDE.  See [docs here](https://fretbursts.readthedocs.io/en/latest/burst_selection.html#module-fretbursts.burstlib).

2. There is no direct way to export the data straight from the figure. It is a feature that can be added and has been discussed before (see issue #17, especially my comment at the end). For exporting the fitted model coefficients, see the relative [example notebook](https://nbviewer.jupyter.org/github/OpenSMFS/FRETBursts_notebooks/blob/master/notebooks/Example%20-%20FRET%20histogram%20fitting.ipynb).

**Comment by mcraj31** [comment]
Thank you for your response.
